### ISSUE TITLE
Delegate work out of services to repositories

### ISSUE THREAD

**Issue by tgiardina** [tgiardina/typescript-typeorm-realworld-example-app#20]

**Comment by kunwar97** [comment]
Hi @tgiardina I want to work on this

**Comment by tgiardina** [comment]
Excellent, it's all yours! I think TypeOrm will do most of the work for you. The roadmap probably looks something like:

1. Delete `services/user` .
2. Refactor `controllers/user` to use `IUserRepository` instead of `IUserService`.
3. Refactor `loaders/container` as appropriate.

Let me know if you have any questions!

**Comment by kunwar97** [comment]
Sure

**Comment by kunwar97** [comment]
@tgiardina What about tests in services/user. Should I delete them or move them to another folder?

**Comment by tgiardina** [comment]
@kunwar97 I think it's fine if you delete them. TypeORM should do everything for you, and there's no need to test that their `save` and `findOne` methods are working correctly. 

Feel free to get rid of `result` and all references to it too. I add it as a helper because I was used to Rust, but it's just making the code more complicated at this point.

**Comment by kunwar97** [comment]
@tgiardina #30

**Comment by tgiardina** [comment]
@kunwar97 Thanks! I'll check it out later today!

**Comment by tgiardina** [comment]
#30 resolved this issue.
