### ISSUE TITLE
Add tsconfig.json

### ISSUE THREAD

**Issue by kunwar97** [tgiardina/typescript-typeorm-realworld-example-app#29]
We need a tsconfig file to add configurations and to fix experimental decorator issues
<img width="889" alt="Screenshot 2020-08-15 at 12 32 48 AM" src="https://user-images.githubusercontent.com/20859901/90284110-08f22d00-de8f-11ea-8f57-8b55d7d14e08.png">

**Comment by kunwar97** [comment]
@tgiardina Should I include this with service refactor?

**Comment by kunwar97** [comment]
@tgiardina #30

**Comment by tgiardina** [comment]
@kunwar97 `tsconfig.json` is located in `/config/general`. Currently, I only run the app using `docker-compose` as described in the [readme](https://github.com/tgiardina/typescript-typeorm-realworld-example-app#installing), which unpacks the config files into the appropriate docker container. This helps avoid system-dependent installation problems.

If you really want to run the app outside of docker container, you could manually copy over the config files to this project's root, but I'm not sure what the benefit of that is.

If you're having trouble getting set up with `docker` and `docker-compose`, I'm happy to help! I really do think it's easier once you get things rolling!
